import Head from 'next/head'
import React from "react";
import { Inter } from '@next/font/google'
import { Navbar, Button, Link, Image, Text, useTheme, Avatar, Dropdown, Modal, Input, Row, Checkbox } from "@nextui-org/react";
import { Layout } from "../compose/liences/LiencesLayout.js";
import { Mail } from "../compose/LoginModel/Mail";
import { Password } from "../compose/LoginModel/Password";
import { icons } from "../compose/Icons.js";

const inter = Inter({ subsets: ['latin'] })

export default function Liences() {
    const { isDark } = useTheme();

    const collapseItems = [
        "features",
        "customers",
        "concepts",
        "liencies",
        "about",
    ];
    const [visible, setVisible] = React.useState(false);
    const handler = () => setVisible(true);
    const closeHandler = () => {
        setVisible(false);
        console.log("closed");
    };
    return (
        <>
            <Head>
                <title>IIo | liences</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="author" content="la niina" />
                <meta name="viewer" content="IIo" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <Layout>
                <Navbar isCompact isBordered={isDark} variant="sticky">
                    <Navbar.Toggle showIn="xs" />
                    <Navbar.Brand
                        css={{
                            "@xs": {
                                w: "12%",
                            },
                        }}
                    >
                        <Image
                            width={30}
                            height={30}
                            src='/logo.svg' />
                        <Text b color="inherit" hideIn="xs">
                            IIo
                        </Text>
                    </Navbar.Brand>

                    <Navbar.Content
                        enableCursorHighlight
                        activeColor="secondary"
                        hideIn="xs"
                        variant="highlight-rounded|underline"
                    >
                        <Navbar.Link href="/">features</Navbar.Link>
                        <Navbar.Link href="/customers">
                            customers
                        </Navbar.Link>
                        <Navbar.Link href="/concepts">concepts</Navbar.Link>
                        <Navbar.Link isActive href="/liences">liences</Navbar.Link>
                        <Dropdown isBordered>
                            <Navbar.Item>
                                <Dropdown.Button
                                    auto
                                    light
                                    css={{
                                        width: '5%',
                                        px: 0,
                                        dflex: "center",
                                        svg: { pe: "none" },
                                    }}
                                    iconRight={icons.chevron}
                                    ripple={false}
                                >
                                    Features
                                </Dropdown.Button>
                            </Navbar.Item>
                            <Dropdown.Menu
                                aria-label="ACME features"
                                css={{
                                    $$dropdownMenuWidth: "340px",
                                    $$dropdownItemHeight: "70px",
                                    "& .nextui-dropdown-item": {
                                        py: "$4",
                                        // dropdown item left icon
                                        svg: {
                                            color: "$secondary",
                                            mr: "$4",
                                        },
                                        // dropdown item title
                                        "& .nextui-dropdown-item-content": {
                                            w: "100%",
                                            fontWeight: "$semibold",
                                        },
                                    },
                                }}
                            >
                                <Dropdown.Item
                                    key="autoscaling"
                                    showFullDescription
                                    description="ACME scales apps to meet user demand, automagically, based on load."
                                >
                                    Autoscaling
                                </Dropdown.Item>
                                <Dropdown.Item
                                    key="usage_metrics"
                                    showFullDescription
                                    description="Real-time metrics to debug issues. Slow query added? We’ll show you exactly where."
                                >
                                    Usage Metrics
                                </Dropdown.Item>
                            </Dropdown.Menu>
                        </Dropdown>
                        <Navbar.Link href="/about">about</Navbar.Link>
                    </Navbar.Content>

                    <Navbar.Content>
                        <Navbar.Item>
                            <Button auto flat as={Link} onClick={handler}>
                                Sign Up
                            </Button>
                        </Navbar.Item>
                    </Navbar.Content>

                    <Modal
                        closeButton
                        preventClose
                        aria-labelledby="modal-title"
                        open={visible}
                        onClose={closeHandler}
                    >
                        <Modal.Header>
                            <Text id="modal-title" size={60}
                                css={{
                                    textGradient: "45deg, $blue600 -20%, $pink600 50%",
                                }}
                                weight="bold">
                                IIo
                            </Text>
                        </Modal.Header>
                        <Modal.Body>
                            <Input
                                clearable
                                bordered
                                fullWidth
                                color="primary"
                                size="lg"
                                placeholder="Email"
                                contentLeft={<Mail fill="currentColor" />}
                            />
                            <Input
                                clearable
                                bordered
                                fullWidth
                                color="primary"
                                size="lg"
                                placeholder="Password"
                                contentLeft={<Password fill="currentColor" />}
                            />
                            <Row justify="space-between">
                                <Checkbox>
                                    <Text size={14}>Remember me</Text>
                                </Checkbox>
                                <Text size={14}>Forgot password?</Text>
                            </Row>
                        </Modal.Body>
                        <Modal.Footer>
                            <Button auto flat color="error" onClick={closeHandler}>
                                Close
                            </Button>
                            <Button auto onClick={closeHandler}>
                                Sign in
                            </Button>
                        </Modal.Footer>
                    </Modal>

                    <Navbar.Collapse>
                        {collapseItems.map((item, index) => (
                            <Navbar.CollapseItem
                                key={item}
                                activeColor="secondary"
                                css={{
                                    color: index === collapseItems.length - 1 ? "$error" : "",
                                }}
                                isActive={index === 2}
                            >
                                <Link
                                    color="inherit"
                                    css={{
                                        minWidth: "100%",
                                    }}
                                    href="#"
                                >
                                    {item}
                                </Link>
                            </Navbar.CollapseItem>
                        ))}
                    </Navbar.Collapse>
                </Navbar>
            </Layout>
        </>
    )
}
